# Generated by Django 3.0.3 on 2020-07-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_profile_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='unnamed.png', null=True, upload_to=''),
        ),
    ]
