# Generated by Django 3.0.3 on 2020-07-05 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200705_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='github_link_link',
            new_name='github_link',
        ),
    ]
